jobs:
  build:
    if: github.repository_owner == 'oshi'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      env:
        COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
        EMAIL: ${{ secrets.EMAIL }}
      name: Analyze with Coverity
      run: "wget -q https://scan.coverity.com/download/linux64 --post-data \"token=$COVERITY_TOKEN&project=oshi%2Foshi\"\
        \ -O coverity_tool.tgz\ntar -xf coverity_tool.tgz\n./cov-analysis-linux64-*/bin/cov-configure\
        \ --java\n./cov-analysis-linux64-*/bin/cov-build --dir cov-int ./mvnw -B -DskipTests=true\
        \ verify\ntar czvf oshi.tgz cov-int\ncurl --form token=$COVERITY_TOKEN \\\n\
        \  --form email=$EMAIL \\\n  --form file=@oshi.tgz \\\n  --form version=\"\
        oshi/coverity_scan\" \\\n  --form description=\"Oshi Coverity Scan\" \\\n\
        \  https://scan.coverity.com/builds?project=oshi%2Foshi\n"
name: Coverity Scan
on:
  repository_dispatch:
    types: trigger-ga___coverity.yaml
