jobs:
  testmatrix:
    name: JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Test with Maven
      run: ./mvnw clean test -B
    - continue-on-error: true
      if: contains(matrix.java, '11') && contains(matrix.os, 'macos-12')
      name: Upload Coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 21
          os: flyci-macos-large-latest-m1
        java:
        - 11
        - 17
        - 21
        os:
        - macos-11
        - macos-12
        - macos-13
        - macos-14
name: macOS CI
on:
  repository_dispatch:
    types: trigger-ga___macos.yaml
