jobs:
  test:
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      if: contains(matrix.os, 'ubuntu') && contains(matrix.java, '11')
      name: Checkstyle
      run: ./mvnw checkstyle:check
    - continue-on-error: true
      if: contains(matrix.os, 'ubuntu') && contains(matrix.java, '11')
      name: Forbidden APIs
      run: ./mvnw compile forbiddenapis:check forbiddenapis:testCheck
    - continue-on-error: true
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos') || contains(matrix.java,
        '11') || contains(matrix.java, '17')
      name: Test with Maven
      run: ./mvnw test -B
    - continue-on-error: true
      if: contains(matrix.java, '11')
      name: Upload Coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 21
          os: flyci-macos-large-latest-m1
        java:
        - 11
        - 17
        - 21
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: Pull Request CI
on:
  repository_dispatch:
    types: trigger-ga___pr.yaml
