jobs:
  build:
    env:
      CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
      CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    if: github.repository_owner == 'oshi' && ! contains(toJSON(github.event.head_commit.message),
      '[maven-release-plugin] prepare release')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Deploy to Sonatype
      run: ./mvnw deploy -Djacoco.skip=true -DskipTests -B --settings ./.mvn/settings.xml
name: Sonatype Snapshot Deployment
on:
  repository_dispatch:
    types: trigger-ga___sonatype.yaml
