jobs:
  testaix:
    concurrency: aix_gcc119
    if: github.repository_owner == 'oshi'
    name: Test JDK 17, aix
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Test in AIX
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 15m
        host: gcc119.fsffrance.org
        key: ${{ secrets.AIX_OSHI_KEY }}
        port: 22
        script: 'rm -fR ~/.cache/JNA

          rm -fR ~/javashared*

          cd ~/git/oshi

          export JAVA_HOME=~/java/jdk-17.0.8.1+1

          export PATH=$PATH:/opt/freeware/bin

          export MAVEN_OPTS="-Xshareclasses:none"

          git checkout master

          git reset --hard HEAD~2

          git pull upstream master

          for i in {1..3}; do ./mvnw clean test -B -Djacoco.skip=true && break ||
          sleep 15; done

          '
        script_stop: true
        username: oshi
  testfreebsd:
    if: github.repository_owner == 'oshi'
    name: Test JDK 11, freebsd
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: test-freebsd
      name: Test in FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        prepare: 'pkg install -y curl

          pkg install -y openjdk11

          '
        run: './mvnw clean test -B -Djacoco.skip=true

          '
        usesh: true
  testopenbsd:
    name: Test JDK 11, OpenBSD vm
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: test-openbsd
      name: Test on OpenBSD
      uses: vmactions/openbsd-vm@v1
      with:
        mem: 2048
        prepare: 'pkg_add curl

          pkg_add jdk%11

          pkg_add maven

          '
        run: 'mvn clean test -B -Djacoco.skip=true

          '
        usesh: false
  testsolaris:
    if: github.repository_owner == 'oshi'
    name: Test JDK 11, Solaris VM
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: test-solaris
      name: Test on Solaris
      uses: vmactions/solaris-vm@v1
      with:
        run: 'wget https://download.bell-sw.com/java/11.0.15.1+2/bellsoft-jdk11.0.15.1+2-solaris-x64-lite.tar.gz
          -nv

          gunzip bellsoft-jdk11.0.15.1+2-solaris-x64-lite.tar.gz

          tar xf bellsoft-jdk11.0.15.1+2-solaris-x64-lite.tar

          rm bellsoft-jdk11.0.15.1+2-solaris-x64-lite.tar

          mv jdk-11.0.15.1-lite /var/tmp

          export JAVA_HOME=/var/tmp/jdk-11.0.15.1-lite

          export PATH=$JAVA_HOME:$PATH

          ./mvnw clean test -B -Djacoco.skip=true -Dmaven.gitcommitid.skip=true

          '
  testsolaris_sparc:
    concurrency: solaris_gcc211
    if: github.repository_owner == 'oshi'
    name: Test JDK 11, Solaris SPARC
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Test in Solaris SPARC
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 25m
        host: gcc211.fsffrance.org
        key: ${{ secrets.AIX_OSHI_KEY }}
        port: 22
        script: 'source .profile

          cd ~/git/oshi

          git checkout master

          git reset --hard HEAD~2

          git pull

          for i in {1..2}; do ./mvnw clean test -B -Djacoco.skip=true -Dlicense.skip=true
          && break || sleep 15; done

          '
        script_stop: true
        username: oshi
name: Unix CI
on:
  repository_dispatch:
    types: trigger-ga___unix.yaml
